export {default as Contact} from './Contact'
export {default as Home} from './Home/Home'
export {default as Kontakt} from './Kontakt/Kontakt'
export {default as NavBar} from './NavBar/NavBar'
export {default as NavigationDots} from './NavigationDots'
export {default as Offers} from './Offers/Offers'
export {default as Projects} from './Projects/Projects'
export {default as UeberUns} from './UeberUns/UeberUns'
